import { Game } from './types';

export const INITIAL_BETTERMATH_GAMES: Game[] = [
  { id: '1', title: '1', image: 'https://5jp1.github.io/theassets/1/meta/apple-touch-icon.png', link: 'https://5jp1.github.io/theassets/1/', source: 'BetterMath' },
  { id: 'TIO', title: 'Territorial Io', image: 'https://tse4.mm.bing.net/th/id/OIP.EFUuDBmcwY4FyMntZK7bxgHaHX?rs=1&pid=ImgDetMain&o=7&rm=3', link: 'https://5jp1.github.io/ter', source: 'BetterMath' },
  { id: '1v1lol', title: 'EaglerCraft', image: 'https://ipindexing.com/media/journal-cover-page/eaglercraft-x-favicon.png', link: 'https://5jp1.github.io/lax1dude', source: 'BetterMath' },
  { id: '1v1space', title: '1v1.space', image: 'https://5jp1.github.io/theassets/1v1space/splash.png', link: 'https://5jp1.github.io/theassets/1v1space/', source: 'BetterMath' },
  { id: '10-minutes-till-dawn', title: '10 Minutes till dawn', image: 'https://5jp1.github.io/theassets/10-minutes-till-dawn/splash.png', link: 'https://5jp1.github.io/theassets/10-minutes-till-dawn/', source: 'BetterMath' },
  { id: '100playerpong', title: '100 Player Pong', image: 'https://5jp1.github.io/theassets/100ng/100ng.jpg', link: 'https://5jp1.github.io/theassets/100ng/', source: 'BetterMath' },
  { id: '2048', title: '2048', image: 'https://5jp1.github.io/theassets/2048/thumb.png', link: 'https://5jp1.github.io/theassets/2048/', source: 'BetterMath' },
  { id: '2048-multitask', title: '2048 Multitask', image: 'https://5jp1.github.io/theassets/2048-multitask/splash.png', link: 'https://5jp1.github.io/theassets/2048-multitask/', source: 'BetterMath' },
  { id: '9007199254740992', title: '9007199254740992', image: 'https://5jp1.github.io/theassets/9007199254740992/logo-4.png', link: 'https://5jp1.github.io/theassets/9007199254740992/', source: 'BetterMath' },
  { id: 'achievementunlocked', title: 'Achievement Unlocked', image: 'https://5jp1.github.io/theassets/achievementunlocked/achievementunlocked.png', link: 'https://5jp1.github.io/theassets/achievementunlocked/', source: 'BetterMath' },
  { id: 'adarkroom', title: 'A Dark Room', image: 'https://5jp1.github.io/theassets/adarkroom/splash.png', link: 'https://5jp1.github.io/theassets/adarkroom/', source: 'BetterMath' },
  { id: 'adrenalinechallenge', title: 'Adrenaline Challenge', image: 'https://5jp1.github.io/theassets/adrenalinechallenge/adrenalinechallenge.jpg', link: 'https://5jp1.github.io/theassets/adrenalinechallenge/', source: 'BetterMath' },
  { id: 'adventuredrivers', title: 'Adventure Drivers', image: 'https://5jp1.github.io/theassets/adventure-drivers/splash.png', link: 'https://5jp1.github.io/theassets/adventure-drivers/', source: 'BetterMath' },
  { id: 'ageofconflict', title: 'Age of Conflict', image: 'https://5jp1.github.io/theassets/ages-of-conflict/splash.jpg', link: 'https://5jp1.github.io/theassets/ages-of-conflict/', source: 'BetterMath' },
  { id: 'alienhominid', title: 'Alien Hominid', image: 'https://5jp1.github.io/theassets/alienhominid/alienhominid.jpg', link: 'https://5jp1.github.io/theassets/alienhominid/', source: 'BetterMath' },
  { id: 'amidsttheclouds', title: 'Amidst the Clouds', image: 'https://5jp1.github.io/theassets/amidst-the-clouds/splash.png', link: 'https://5jp1.github.io/theassets/amidst-the-clouds/', source: 'BetterMath' },
  { id: 'among-us', title: 'Among Us', image: 'https://5jp1.github.io/theassets/among-us/red.png', link: 'https://5jp1.github.io/theassets/among-us/', source: 'BetterMath' },
  { id: 'angrysharks', title: 'Angry Sharks', image: 'https://5jp1.github.io/theassets/angry-sharks/assets/favicon/icon-512x512.png', link: 'https://5jp1.github.io/theassets/angry-sharks/', source: 'BetterMath' },
  { id: 'aquaparkslides', title: 'Aquapark slides', image: 'https://5jp1.github.io/theassets/aquapark-slides/splash.png', link: 'https://5jp1.github.io/theassets/aquapark-slides/', source: 'BetterMath' },
  { id: 'avalanche', title: 'Avalanche', image: 'https://5jp1.github.io/theassets/avalanche/avalanche.png', link: 'https://5jp1.github.io/theassets/avalanche/', source: 'BetterMath' },
  { id: 'awesometanks2', title: 'Awesome Tanks 2', image: 'https://5jp1.github.io/theassets/awesometanks2/images/menu/logo.jpg', link: 'https://5jp1.github.io/theassets/awesometanks2/', source: 'BetterMath' },
  { id: 'backrooms', title: 'Backrooms', image: 'https://5jp1.github.io/theassets/backrooms/img/splash.jpg', link: 'https://5jp1.github.io/theassets/backrooms/', source: 'BetterMath' },
  { id: 'badicecream', title: 'Bad Ice Cream', image: 'https://5jp1.github.io/theassets/bad-ice-cream/bad-ice-cream.png', link: 'https://5jp1.github.io/theassets/bad-ice-cream/', source: 'BetterMath' },
  { id: 'badicecream2', title: 'Bad Ice Cream 2', image: 'https://5jp1.github.io/theassets/bad-ice-cream-2/bad-ice-cream-2.png', link: 'https://5jp1.github.io/theassets/bad-ice-cream-2/', source: 'BetterMath' },
  { id: 'badicecream3', title: 'Bad Ice Cream 3', image: 'https://5jp1.github.io/theassets/bad-ice-cream-3/bad-ice-cream-3.png', link: 'https://5jp1.github.io/theassets/bad-ice-cream-3/', source: 'BetterMath' },
  { id: 'baldisbasics', title: "Baldi's Basics", image: 'https://5jp1.github.io/theassets/baldis-basics/splash.png', link: 'https://5jp1.github.io/theassets/baldis-basics/', source: 'BetterMath' },
  { id: 'ballisticchickens', title: 'Ballistic Chickens', image: 'https://5jp1.github.io/theassets/ballistic-chickens/logo.png', link: 'https://5jp1.github.io/theassets/ballistic-chickens/', source: 'BetterMath' },
  { id: 'basketballstars', title: 'Basketball Stars', image: 'https://5jp1.github.io/theassets/basketball-stars/assets/images/basketball-stars.png', link: 'https://5jp1.github.io/theassets/basketball-stars/', source: 'BetterMath' },
  { id: 'basketbros', title: 'Basketbros.io', image: 'https://5jp1.github.io/theassets/basketbros-io/thumb.jpg', link: 'https://5jp1.github.io/theassets/basketbros-io/', source: 'BetterMath' },
  { id: 'battleforgondor', title: 'Battle for Gondor', image: 'https://5jp1.github.io/theassets/battleforgondor/battleforgondor.JPG', link: 'https://5jp1.github.io/theassets/battleforgondor/', source: 'BetterMath' },
  { id: 'bigredbutton', title: 'Big Red Button', image: 'https://5jp1.github.io/theassets/bigredbutton/bigredbutton.png', link: 'https://5jp1.github.io/theassets/bigredbutton/', source: 'BetterMath' },
  { id: 'bitlife', title: 'Bitlife', image: 'https://5jp1.github.io/theassets/bitlife/logo.png', link: 'https://5jp1.github.io/theassets/bitlife/', source: 'BetterMath' },
  { id: 'blackholesquare', title: 'Black Hole Square', image: 'https://5jp1.github.io/theassets/blacholesquare/icon.png', link: 'https://5jp1.github.io/theassets/blacholesquare/', source: 'BetterMath' },
  { id: 'blackknight', title: 'Black Knight', image: 'https://5jp1.github.io/theassets/blackknight/blackknight.png', link: 'https://5jp1.github.io/theassets/blackknight/', source: 'BetterMath' },
  { id: 'bloonstd', title: 'Bloons TD', image: 'https://5jp1.github.io/theassets/bloonstd/bloonstd.jpg', link: 'https://5jp1.github.io/theassets/bloonstd/', source: 'BetterMath' },
  { id: 'bloonstd2', title: 'Bloons TD 2', image: 'https://5jp1.github.io/theassets/bloonstd2/bloonstd2.png', link: 'https://5jp1.github.io/theassets/bloonstd2/', source: 'BetterMath' },
  { id: 'bloxors', title: 'Bloxors', image: 'https://5jp1.github.io/theassets/bloxors/block.png', link: 'https://5jp1.github.io/theassets/bloxors/', source: 'BetterMath' },
  { id: 'bobtherobber2', title: 'Bob the Robber 2', image: 'https://5jp1.github.io/theassets/bobtherobber2/splash.jpeg', link: 'https://5jp1.github.io/theassets/bobtherobber2/', source: 'BetterMath' },
  { id: 'boxhead', title: 'Box Head', image: 'https://5jp1.github.io/theassets/boxhead2play/boxhead2play.jpg', link: 'https://5jp1.github.io/theassets/boxhead2play/', source: 'BetterMath' },
  { id: 'boxingrandom', title: 'Boxing Random', image: 'https://5jp1.github.io/theassets/boxing-random/512x512.jpg', link: 'https://5jp1.github.io/theassets/boxing-random/', source: 'BetterMath' },
  { id: 'breakingthebank', title: 'Breaking the Bank', image: 'https://5jp1.github.io/theassets/breakingthebank/breakingthebank.png', link: 'https://5jp1.github.io/theassets/breakingthebank/', source: 'BetterMath' },
  { id: 'btts', title: 'Big Tower Tiny Square', image: 'https://5jp1.github.io/theassets/btts/images.png', link: 'https://5jp1.github.io/theassets/btts/', source: 'BetterMath' },
  { id: 'bntts', title: 'Big NEON Tower Tiny Square', image: 'https://5jp1.github.io/theassets/bntts/icons/icon-256.png', link: 'https://5jp1.github.io/theassets/bntts/', source: 'BetterMath' },
  { id: 'burgerfrights', title: 'Burger and Frights', image: 'https://5jp1.github.io/theassets/burger-and-frights/splash.png', link: 'https://5jp1.github.io/theassets/burger-and-frights/', source: 'BetterMath' },
  { id: 'cannonbasketball4', title: 'Cannon Basketball 4', image: 'https://5jp1.github.io/theassets/cannon-basketball-4/img/splash.png', link: 'https://5jp1.github.io/theassets/cannon-basketball-4/', source: 'BetterMath' },
  { id: 'canyondefense', title: 'Canyon Defense', image: 'https://5jp1.github.io/theassets/canyondefense/canyondefense.png', link: 'https://5jp1.github.io/theassets/canyondefense/', source: 'BetterMath' },
  { id: 'carssimulator', title: 'Cars Simulator', image: 'https://5jp1.github.io/theassets/cars-simulator/splash.png', link: 'https://5jp1.github.io/theassets/cars-simulator/', source: 'BetterMath' },
  { id: 'cellmachine', title: 'Cell Machine', image: 'https://5jp1.github.io/theassets/cell-machine/img/te9nDu.png', link: 'https://5jp1.github.io/theassets/cell-machine/', source: 'BetterMath' },
  { id: 'championisland', title: 'Champion Island', image: 'https://5jp1.github.io/theassets/champion-island/splash.png', link: 'https://5jp1.github.io/theassets/champion-island/', source: 'BetterMath' },
  { id: 'championarcher', title: 'Champion Archer', image: 'https://5jp1.github.io/theassets/championarcher/championarcher.png', link: 'https://5jp1.github.io/theassets/championarcher/', source: 'BetterMath' },
  { id: 'chillradio', title: 'Chill Radio', image: 'https://5jp1.github.io/theassets/chill-radio/img/icon.png', link: 'https://5jp1.github.io/theassets/chill-radio/', source: 'BetterMath' },
  { id: 'chromedino', title: 'Chrome Dino', image: 'https://5jp1.github.io/theassets/chrome-dino/icons/icon-256.png', link: 'https://5jp1.github.io/theassets/chrome-dino/', source: 'BetterMath' },
  { id: 'circlo', title: 'circlO', image: 'https://5jp1.github.io/theassets/circlo/img/download.png', link: 'https://5jp1.github.io/theassets/circlo/', source: 'BetterMath' },
  { id: 'clusterrush', title: 'Cluster Rush', image: 'https://5jp1.github.io/theassets/cluster-rush/splash.png', link: 'https://5jp1.github.io/theassets/cluster-rush/', source: 'BetterMath' },
  { id: 'tabletennisultimate', title: 'Table Tennis Ultimate', image: 'https://5jp1.github.io/theassets/cnpingpong/tabletennisultimate.png', link: 'https://5jp1.github.io/theassets/cnpingpong/', source: 'BetterMath' },
  { id: 'connect3', title: 'Connect 3', image: 'https://5jp1.github.io/theassets/connect3/connect3.png', link: 'https://5jp1.github.io/theassets/connect3/', source: 'BetterMath' },
  { id: 'cookieclicker', title: 'Cookie Clicker', image: 'https://5jp1.github.io/theassets/cookie-clicker/cookie1.jpeg', link: 'https://5jp1.github.io/theassets/cookie-clicker/', source: 'BetterMath' },
  { id: 'coreball', title: 'Core Ball', image: 'https://5jp1.github.io/theassets/core-ball/pr_source.png', link: 'https://5jp1.github.io/theassets/core-ball/', source: 'BetterMath' },
  { id: 'craftmine', title: 'CraftMine', image: 'https://5jp1.github.io/theassets/craftmine/images/craftmine.png', link: 'https://5jp1.github.io/theassets/craftmine/', source: 'BetterMath' },
  { id: 'creativekillchamber', title: 'Creative Kill Chamber', image: 'https://5jp1.github.io/theassets/creativekillchamber/creativekillchamber.jpg', link: 'https://5jp1.github.io/theassets/creativekillchamber/', source: 'BetterMath' },
  { id: 'crossyroad', title: 'Crossy Road', image: 'https://5jp1.github.io/theassets/crossyroad/crossyroad.png', link: 'https://5jp1.github.io/theassets/crossyroad/', source: 'BetterMath' },
  { id: 'csgoclicker', title: 'CS:GO Clicker', image: 'https://5jp1.github.io/theassets/csgo-clicker/images/vanguard.png', link: 'https://5jp1.github.io/theassets/csgo-clicker/', source: 'BetterMath' },
  { id: 'ctr', title: 'Cut the Rope', image: 'https://5jp1.github.io/theassets/ctr/logo.png', link: 'https://5jp1.github.io/theassets/ctr/', source: 'BetterMath' },
  { id: 'ctrholiday', title: 'Cut the Rope Holiday', image: 'https://5jp1.github.io/theassets/ctr-holiday/Holiday_Gift.webp', link: 'https://5jp1.github.io/theassets/ctr-holiday/', source: 'BetterMath' },
  { id: 'ctrtt', title: 'Cut the Rope Time Travel', image: 'https://5jp1.github.io/theassets/ctr-tr/logo.png', link: 'https://5jp1.github.io/theassets/ctr-tr/', source: 'BetterMath' },
  { id: 'cubefield', title: 'Cubefield', image: 'https://5jp1.github.io/theassets/cubefield/assets/unnamed.png', link: 'https://5jp1.github.io/theassets/cubefield/', source: 'BetterMath' },
  { id: 'cupcake2048', title: 'Cupcake 2048', image: 'https://5jp1.github.io/theassets/cupcake2048/favicon.png', link: 'https://5jp1.github.io/theassets/cupcake2048/', source: 'BetterMath' },
  { id: 'dante', title: 'Dante', image: 'https://5jp1.github.io/theassets/dante/splash.png', link: 'https://5jp1.github.io/theassets/dante/', source: 'BetterMath' },
  { id: 'dealornodeal', title: 'Deal or No Deal', image: 'https://5jp1.github.io/theassets/deal-or-no-deal/index.jpg', link: 'https://5jp1.github.io/theassets/deal-or-no-deal/', source: 'BetterMath' },
  { id: 'deathrun3d', title: 'Death Run 3D', image: 'https://5jp1.github.io/theassets/death-run-3d/img/death.png', link: 'https://5jp1.github.io/theassets/death-run-3d/', source: 'BetterMath' },
  { id: 'defendthetank', title: 'Defend the Tank', image: 'https://5jp1.github.io/theassets/defend-the-tank/images/splash.jpg', link: 'https://5jp1.github.io/theassets/defend-the-tank/', source: 'BetterMath' },
  { id: 'doctoracorn2', title: 'Doctor Acorn 2', image: 'https://5jp1.github.io/theassets/doctor-acorn2/splash.jpg', link: 'https://5jp1.github.io/theassets/doctor-acorn2/', source: 'BetterMath' },
  { id: 'doge2048', title: 'Doge 2048', image: 'https://5jp1.github.io/theassets/doge2048/meta/apple-touch-icon.png', link: 'https://5jp1.github.io/theassets/doge2048/', source: 'BetterMath' },
  { id: 'dogeminer', title: 'Doge Miner', image: 'https://5jp1.github.io/theassets/DogeMiner/img/dogeminer_300x300.png', link: 'https://5jp1.github.io/theassets/dogeminer/', source: 'BetterMath' },
  { id: 'doodlejump', title: 'Doodle Jump', image: 'https://5jp1.github.io/theassets/doodle-jump/doodle.png', link: 'https://5jp1.github.io/theassets/doodle-jump/', source: 'BetterMath' },
  { id: 'doublewires', title: 'Double Wires', image: 'https://5jp1.github.io/theassets/doublewires/doublewires.png', link: 'https://5jp1.github.io/theassets/doublewires/', source: 'BetterMath' },
  { id: 'dragonsvsbricks', title: 'Dragons vs Bricks', image: 'https://5jp1.github.io/theassets/dragon-vs-bricks/icon.jpg', link: 'https://5jp1.github.io/theassets/dragon-vs-bricks/', source: 'BetterMath' },
  { id: 'drawthehill', title: 'Draw the Hill', image: 'https://5jp1.github.io/theassets/draw-the-hill/icons/icon-512.png', link: 'https://5jp1.github.io/theassets/draw-the-hill/', source: 'BetterMath' },
  { id: 'drivemad', title: 'Drive Mad', image: 'https://5jp1.github.io/theassets/drive-mad/logo.jpg', link: 'https://5jp1.github.io/theassets/drive-mad/', source: 'BetterMath' },
  { id: 'ducklife', title: 'Duck Life', image: 'https://5jp1.github.io/theassets/ducklife1/ducklife.png', link: 'https://5jp1.github.io/theassets/ducklife1/', source: 'BetterMath' },
  { id: 'ducklife2', title: 'Duck Life 2', image: 'https://5jp1.github.io/theassets/ducklife2/ducklife2.png', link: 'https://5jp1.github.io/theassets/ducklife2/', source: 'BetterMath' },
  { id: 'ducklife3', title: 'Duck Life 3', image: 'https://5jp1.github.io/theassets/ducklife3/duck.png', link: 'https://5jp1.github.io/theassets/ducklife3/', source: 'BetterMath' },
  { id: 'ducklife4', title: 'Duck Life 4', image: 'https://5jp1.github.io/theassets/ducklife4/splash.jpg', link: 'https://5jp1.github.io/theassets/ducklife4/', source: 'BetterMath' },
  { id: 'edgesurf', title: "Edge Let's surf", image: 'https://5jp1.github.io/theassets/edge-surf/splash.png', link: 'https://5jp1.github.io/theassets/edge-surf/', source: 'BetterMath' },
  { id: 'edgenotfound', title: 'Edge Not Found', image: 'https://5jp1.github.io/theassets/edgenotfound/edge.png', link: 'https://5jp1.github.io/theassets/edgenotfound/', source: 'BetterMath' },
  { id: 'eelslap', title: 'Eel Slap', image: 'https://5jp1.github.io/theassets/eel-slap/eel-slap.png', link: 'https://5jp1.github.io/theassets/eel-slap/', source: 'BetterMath' },
  { id: 'elasticman', title: 'Elastic Man', image: 'https://5jp1.github.io/theassets/elasticman/elasticman.jpg', link: 'https://5jp1.github.io/theassets/elasticman/', source: 'BetterMath' },
  { id: 'endlesswar3', title: 'Endless War 3', image: 'https://5jp1.github.io/theassets/endlesswar3/endlesswar3.png', link: 'https://5jp1.github.io/theassets/endlesswar3/', source: 'BetterMath' },
  { id: 'escapingtheprison', title: 'Escaping The Prison', image: 'https://5jp1.github.io/theassets/escapingtheprison/escapingtheprison.jpg', link: 'https://5jp1.github.io/theassets/escapingtheprison/', source: 'BetterMath' },
  { id: 'evilglitch', title: 'Evil Glitch', image: 'https://5jp1.github.io/theassets/evil-glitch/evil.png', link: 'https://5jp1.github.io/theassets/evil-glitch/', source: 'BetterMath' },
  { id: 'evolution', title: 'Evolution', image: 'https://5jp1.github.io/theassets/evolution/splash.png', link: 'https://5jp1.github.io/theassets/evolution/', source: 'BetterMath' },
  { id: 'exo', title: 'Exo', image: 'https://5jp1.github.io/theassets/exo/img/small.jpg', link: 'https://5jp1.github.io/theassets/exo/', source: 'BetterMath' },
  { id: 'factoryballs', title: 'Factory Balls Forever', image: 'https://5jp1.github.io/theassets/factoryballs/images/splash.png', link: 'https://5jp1.github.io/theassets/factoryballs/', source: 'BetterMath' },
  { id: 'fairsquares', title: 'Fair Squares', image: 'https://5jp1.github.io/theassets/fairsquares/index.apple-touch-icon.png', link: 'https://5jp1.github.io/theassets/fairsquares/', source: 'BetterMath' },
  { id: 'fancypants', title: 'Fancy Pants Adventures', image: 'https://5jp1.github.io/theassets/fancypantsadventures/fancypantsadventure.png', link: 'https://5jp1.github.io/theassets/fancypantsadventures/', source: 'BetterMath' },
  { id: 'fakevirus', title: 'Fake Virus', image: 'https://5jp1.github.io/theassets/fake-virus/icon.png', link: 'https://5jp1.github.io/theassets/fake-virus/', source: 'BetterMath' },
  { id: 'fireboywatergirl', title: 'Fireboy and Watergirl', image: 'https://5jp1.github.io/theassets/fireboywatergirlforesttemple/logo.jpeg', link: 'https://5jp1.github.io/theassets/fireboywatergirlforesttemple/', source: 'BetterMath' },
  { id: 'flappy2048', title: 'Flappy 2048', image: 'https://5jp1.github.io/theassets/flappy-2048/meta/apple-touch-icon.png', link: 'https://5jp1.github.io/theassets/flappy-2048/', source: 'BetterMath' },
  { id: 'flappybird', title: 'Flappy Bird', image: 'https://5jp1.github.io/theassets/flappy-bird/assets/thumb.png', link: 'https://5jp1.github.io/theassets/flappybird/', source: 'BetterMath' },
  { id: 'flashtetris', title: 'Flash Tetris', image: 'https://5jp1.github.io/theassets/flashtetris/flashtetris.png', link: 'https://5jp1.github.io/theassets/flashtetris/', source: 'BetterMath' },
  { id: 'flippyfish', title: 'Flippy Fish', image: 'https://5jp1.github.io/theassets/flippy-fish/2022_10_28_0jt_Kleki.png', link: 'https://5jp1.github.io/theassets/flippy-fish/', source: 'BetterMath' },
  { id: 'fnaw', title: "Five Nights at Winston's", image: 'https://5jp1.github.io/theassets/fnaw/splash.png', link: 'https://5jp1.github.io/theassets/fnaw/', source: 'BetterMath' },
  { id: 'fnf', title: "Friday Night Funkin'", image: 'https://5jp1.github.io/theassets/fridaynightfunkin/fnf-icon.jpg', link: 'https://5jp1.github.io/theassets/fridaynightfunkin/', source: 'BetterMath' },
  { id: 'froggysbattle', title: "Froggy's Battle", image: 'https://5jp1.github.io/theassets/froggys-battle/splash.png', link: 'https://5jp1.github.io/theassets/froggys-battle/', source: 'BetterMath' },
  { id: 'fruitninja', title: 'Fruit Ninja', image: 'https://5jp1.github.io/theassets/fruitninja/FruitNinjaTeaser.jpg', link: 'https://5jp1.github.io/theassets/fruitninja/', source: 'BetterMath' },
  { id: 'fryingnemo', title: 'Frying Nemo', image: 'https://5jp1.github.io/theassets/frying-nemo/splash.png', link: 'https://5jp1.github.io/theassets/frying-nemo/', source: 'BetterMath' },
  { id: 'gameinside', title: 'Game Inside a Game...', image: 'https://5jp1.github.io/theassets/game-inside/img/display.png', link: 'https://5jp1.github.io/theassets/game-inside/', source: 'BetterMath' },
  { id: 'genericfishing', title: 'Generic Fishing Game', image: 'https://5jp1.github.io/theassets/generic-fishing-game/splash.png', link: 'https://5jp1.github.io/theassets/generic-fishing-game/', source: 'BetterMath' },
  { id: 'geodashscratch', title: 'Geometry Dash (Scratch)', image: 'https://5jp1.github.io/theassets/geodash/geoscratchicon.png', link: 'https://5jp1.github.io/theassets/geodash/', source: 'BetterMath' },
  { id: 'georgeprinter', title: 'George and the Printer', image: 'https://5jp1.github.io/theassets/georgeandtheprinter/img/SnDTEn.png', link: 'https://5jp1.github.io/theassets/georgeandtheprinter/', source: 'BetterMath' },
  { id: 'getawayshootout', title: 'Getaway Shootout', image: 'https://5jp1.github.io/theassets/getaway-shootout/img/images.jpg', link: 'https://5jp1.github.io/theassets/getaway-shootout/', source: 'BetterMath' },
  { id: 'gimmeairpod', title: 'Gimme the Airpod', image: 'https://5jp1.github.io/theassets/gimme-the-airpod/img/logo.png', link: 'https://5jp1.github.io/theassets/gimme-the-airpod/', source: 'BetterMath' },
  { id: 'glasscity', title: 'Glass City', image: 'https://5jp1.github.io/theassets/glass-city/image.png', link: 'https://5jp1.github.io/theassets/glass-city/', source: 'BetterMath' },
  { id: 'goball', title: 'Go Ball', image: 'https://5jp1.github.io/theassets/go-ball/game.jpg', link: 'https://5jp1.github.io/theassets/go-ball/', source: 'BetterMath' },
  { id: 'goodnight', title: 'GOODNIGHT', image: 'https://5jp1.github.io/theassets/goodnight/goodnight.jpg', link: 'https://5jp1.github.io/theassets/goodnight/', source: 'BetterMath' },
  { id: 'googlefeud', title: 'Google Feud', image: 'https://5jp1.github.io/theassets/google-feud/splash.png', link: 'https://5jp1.github.io/theassets/google-feud/', source: 'BetterMath' },
  { id: 'googlesnake', title: 'Google Snake', image: 'https://5jp1.github.io/theassets/google-snake/img/snake.png', link: 'https://5jp1.github.io/theassets/google-snake/', source: 'BetterMath' },
  { id: 'gravitysoccer', title: 'Gravity Soccer', image: 'https://5jp1.github.io/theassets/gravity-soccer/splash.png', link: 'https://5jp1.github.io/theassets/gravity-soccer/', source: 'BetterMath' },
  { id: 'greybox', title: 'Grey Box Testing', image: 'https://5jp1.github.io/theassets/greybox/ico.png', link: 'https://5jp1.github.io/theassets/greybox/', source: 'BetterMath' },
  { id: 'grindcraft', title: 'Grind Craft', image: 'https://5jp1.github.io/theassets/grindcraft/img/splash.png', link: 'https://5jp1.github.io/theassets/grindcraft/', source: 'BetterMath' },
  { id: 'hackertyper', title: 'Hacker Typer', image: 'https://5jp1.github.io/theassets/hackertype/logo192.png', link: 'https://5jp1.github.io/theassets/hackertype/', source: 'BetterMath' },
  { id: 'handshakes', title: 'Handshakes', image: 'https://5jp1.github.io/theassets/handshakes/splaher.png', link: 'https://5jp1.github.io/theassets/handshakes/', source: 'BetterMath' },
  { id: 'happyhop', title: 'Happy Hop', image: 'https://5jp1.github.io/theassets/happy-hop/splash.png', link: 'https://5jp1.github.io/theassets/happy-hop/', source: 'BetterMath' },
  { id: 'hba', title: 'Hover Bot Arena', image: 'https://5jp1.github.io/theassets/hba/hoverbotarena.JPG', link: 'https://5jp1.github.io/theassets/hba/', source: 'BetterMath' },
  { id: 'helicopter', title: 'Helicopter', image: 'https://5jp1.github.io/theassets/helicopter/helicopter.png', link: 'https://5jp1.github.io/theassets/helicopter/', source: 'BetterMath' },
  { id: 'hexempire', title: 'Hex Empire', image: 'https://5jp1.github.io/theassets/hexempire/hexempire.jpg', link: 'https://5jp1.github.io/theassets/hexempire/', source: 'BetterMath' },
  { id: 'hexgl', title: 'HexGL', image: 'https://5jp1.github.io/theassets/HexGL/Hexgl-image-1.jpg', link: 'https://5jp1.github.io/theassets/hexgl/', source: 'BetterMath' },
  { id: 'hextris', title: 'Hextris', image: 'https://5jp1.github.io/theassets/hextris/images/hextris-logo.png', link: 'https://5jp1.github.io/theassets/hextris/', source: 'BetterMath' },
  { id: 'hungrylamu', title: 'Hungry Lamu', image: 'https://5jp1.github.io/theassets/hungry-lamu/splash.png', link: 'https://5jp1.github.io/theassets/hungry-lamu/', source: 'BetterMath' },
  { id: 'idlebreakout', title: 'Idle Breakout', image: 'https://5jp1.github.io/theassets/idle-breakout/img/thumbnail.png', link: 'https://5jp1.github.io/theassets/idle-breakout/', source: 'BetterMath' },
  { id: 'idleshark', title: 'Idle Shark', image: 'https://5jp1.github.io/theassets/idle-shark/img/sharkgame.png', link: 'https://5jp1.github.io/theassets/idle-shark/', source: 'BetterMath' },
  { id: 'impossiblequiz', title: 'Impossible Quiz', image: 'https://5jp1.github.io/theassets/impossiblequiz/impossiblequiz.png', link: 'https://5jp1.github.io/theassets/impossiblequiz/', source: 'BetterMath' },
  { id: 'interactivebuddy', title: 'Interactive Buddy', image: 'https://5jp1.github.io/theassets/interactivebuddy/interactivebuddy.jpg', link: 'https://5jp1.github.io/theassets/interactivebuddy/', source: 'BetterMath' },
  { id: 'jetpackjoyride', title: 'Jetpack Joyride', image: 'https://5jp1.github.io/theassets/jetpack-joyride/splash.jpg', link: 'https://5jp1.github.io/theassets/jetpack-joyride/', source: 'BetterMath' },
  { id: 'justfall', title: 'JustFall.lol', image: 'https://5jp1.github.io/theassets/just-fall/unnamed.png', link: 'https://5jp1.github.io/theassets/just-fall/', source: 'BetterMath' },
  { id: 'justoneboss', title: 'Just One Boss', image: 'https://5jp1.github.io/theassets/just-one-boss/pv1Gr5.png', link: 'https://5jp1.github.io/theassets/just-one-boss/', source: 'BetterMath' },
  { id: 'kitchengungame', title: 'Kitchen gun game', image: 'https://5jp1.github.io/theassets/kitchen-gun-game/splash.png', link: 'https://5jp1.github.io/theassets/kitchen-gun-game/', source: 'BetterMath' },
  { id: 'kittencannon', title: 'Kitten Cannon', image: 'https://5jp1.github.io/theassets/kittencannon/kittencannon.png', link: 'https://5jp1.github.io/theassets/kittencannon/', source: 'BetterMath' },
  { id: 'knifemaster', title: 'Knife Master', image: 'https://5jp1.github.io/theassets/knife-master/512x512.jpg', link: 'https://5jp1.github.io/theassets/knife-master/', source: 'BetterMath' },
  { id: 'krunker', title: 'Krunker', image: 'https://5jp1.github.io/theassets/krunker/img/krunker-io.jpg', link: 'https://5jp1.github.io/theassets/krunker/', source: 'BetterMath' },
  { id: 'learntofly', title: 'Learn To Fly', image: 'https://5jp1.github.io/theassets/learntofly/learntofly.png', link: 'https://5jp1.github.io/theassets/learntofly/', source: 'BetterMath' },
  { id: 'learntofly2', title: 'Learn to fly 2', image: 'https://5jp1.github.io/theassets/learntofly2/learn-to-fly-2.jpg', link: 'https://5jp1.github.io/theassets/learntofly2/', source: 'BetterMath' },
  { id: 'madalinstuntcars2', title: 'Madalin Stunt Cars 2', image: 'https://5jp1.github.io/theassets/madalin-stunt-cars-2/img/logo.jpg', link: 'https://5jp1.github.io/theassets/madalin-stunt-cars-2/', source: 'BetterMath' },
  { id: 'madalinstuntcars3', title: 'Madalin Stunt Cars 3', image: 'https://5jp1.github.io/theassets/madalin-stunt-cars-3/img/index.jpg', link: 'https://5jp1.github.io/theassets/madalin-stunt-cars-3/', source: 'BetterMath' },
  { id: 'mario', title: 'Mario', image: 'https://5jp1.github.io/theassets/mario/Theme/Mario.gif', link: 'https://5jp1.github.io/theassets/mario/', source: 'BetterMath' },
  { id: 'marvinspectrum', title: 'Marvin Spectrum', image: 'https://5jp1.github.io/theassets/marvinspectrum/marvinspectrum.png', link: 'https://5jp1.github.io/theassets/marvinspectrum/', source: 'BetterMath' },
  { id: 'matrixrampage', title: 'Matrix Rampage', image: 'https://5jp1.github.io/theassets/matrixrampage/matrixrampage.jpg', link: 'https://5jp1.github.io/theassets/matrixrampage/', source: 'BetterMath' },
  { id: 'meme2048', title: 'Meme 2048', image: 'https://5jp1.github.io/theassets/meme2048/img/rickroll.gif', link: 'https://5jp1.github.io/theassets/meme2048/', source: 'BetterMath' },
  { id: 'mergeroundracers', title: 'Merge Round Racers', image: 'https://5jp1.github.io/theassets/merge-round-racers/splash.png', link: 'https://5jp1.github.io/theassets/merge-round-racers/', source: 'BetterMath' },
  { id: 'mineblocks', title: 'Mine Blocks', image: 'https://5jp1.github.io/theassets/mineblocks/splash.png', link: 'https://5jp1.github.io/theassets/mineblocks/', source: 'BetterMath' },
  { id: 'minecraft-15', title: 'Eaglercraft 1.5', image: 'https://5jp1.github.io/theassets/minecraft-15/splash.jpeg', link: 'https://5jp1.github.io/theassets/minecraft-15/', source: 'BetterMath' },
  { id: 'minecraft-18', title: 'Eaglercraft 1.8', image: 'https://5jp1.github.io/theassets/minecraft-18/splash.png', link: 'https://5jp1.github.io/theassets/minecraft-18/', source: 'BetterMath' },
  { id: 'minecraftclassic', title: 'Minecraft Classic', image: 'https://5jp1.github.io/theassets/minecraft-classic/pack.png', link: 'https://5jp1.github.io/theassets/minecraft-classic/', source: 'BetterMath' },
  { id: 'minecraftclassichacks', title: 'Minecraft Classic Hacks', image: 'https://5jp1.github.io/theassets/minecraftbeta/bg_main.png', link: 'https://5jp1.github.io/theassets/minecraftbeta/', source: 'BetterMath' },
  { id: 'minesweeper', title: 'Minesweeper', image: 'https://5jp1.github.io/theassets/minesweeper/img/minesweeper.png', link: 'https://5jp1.github.io/theassets/minesweeper/', source: 'BetterMath' },
  { id: 'miniputt', title: 'Mini-putt', image: 'https://5jp1.github.io/theassets/miniputt/miniputt.png', link: 'https://5jp1.github.io/theassets/miniputt/', source: 'BetterMath' },
  { id: 'missiles', title: 'Missiles', image: 'https://5jp1.github.io/theassets/missiles/miss.png', link: 'https://5jp1.github.io/theassets/missiles/', source: 'BetterMath' },
  { id: 'motox3m', title: 'MotoX3M', image: 'https://5jp1.github.io/theassets/motox3m/splash.jpg', link: 'https://5jp1.github.io/theassets/motox3m/', source: 'BetterMath' },
  { id: 'motox3m2', title: 'MotoX3M 2', image: 'https://5jp1.github.io/theassets/motox3m/splash.jpg', link: 'https://5jp1.github.io/theassets/motox3m2/', source: 'BetterMath' },
  { id: 'motox3mpool', title: 'MotoX3M Pool', image: 'https://5jp1.github.io/theassets/motox3m-pool/splash.jpg', link: 'https://5jp1.github.io/theassets/motox3m-pool/', source: 'BetterMath' },
  { id: 'motox3mspooky', title: 'MotoX3M Spooky', image: 'https://5jp1.github.io/theassets/motox3m-spooky/splash.jpeg', link: 'https://5jp1.github.io/theassets/motox3m-spooky/', source: 'BetterMath' },
  { id: 'motox3mwinter', title: 'MotoX3M Winter', image: 'https://5jp1.github.io/theassets/motox3m-winter/download.jpeg', link: 'https://5jp1.github.io/theassets/motox3m-winter/', source: 'BetterMath' },
  { id: 'rustysubmarine', title: 'My Rusty Submarine', image: 'https://5jp1.github.io/theassets/my-rusty-submarine/splash.png', link: 'https://5jp1.github.io/theassets/my-rusty-submarine/', source: 'BetterMath' },
  { id: 'ngon', title: 'n-gon', image: 'https://5jp1.github.io/theassets/n-gon/bot.png', link: 'https://5jp1.github.io/theassets/n-gon/', source: 'BetterMath' },
  { id: 'ninja', title: 'Ninja', image: 'https://5jp1.github.io/theassets/ninja/logo1.png', link: 'https://5jp1.github.io/theassets/ninja/', source: 'BetterMath' },
  { id: 'ninjavsevilcorp', title: 'Ninja vs Evil Corp', image: 'https://5jp1.github.io/theassets/ninjavsevilcorp/splash.png', link: 'https://5jp1.github.io/theassets/ninjavsevilcorp/', source: 'BetterMath' },
  { id: 'noobsteveparkour', title: 'Noob Steve Parkour', image: 'https://5jp1.github.io/theassets/noob-steve-parkour/512x512.jpg', link: 'https://5jp1.github.io/theassets/noob-steve-parkour/', source: 'BetterMath' },
  { id: 'nsshaft', title: 'NS-Shaft', image: 'https://5jp1.github.io/theassets/ns-shaft/favicon.png', link: 'https://5jp1.github.io/theassets/ns-shaft/', source: 'BetterMath' },
  { id: 'nsresurgence', title: 'Neon Square Resurgence', image: 'https://5jp1.github.io/theassets/nsresurgence/neon.png', link: 'https://5jp1.github.io/theassets/nsresurgence/', source: 'BetterMath' },
  { id: 'offlineparadise', title: 'Offline Paradise', image: 'https://5jp1.github.io/theassets/OfflineParadise/assets/icon.jpeg', link: 'https://5jp1.github.io/theassets/offlineparadise/', source: 'BetterMath' },
  { id: 'omnombounce', title: 'Om Nom Bounce', image: 'https://5jp1.github.io/theassets/om-bounce/assets/icon.jpeg', link: 'https://5jp1.github.io/theassets/om-bounce/', source: 'BetterMath' },
  { id: 'ovo', title: 'OvO', image: 'https://5jp1.github.io/theassets/ovo/ovo.png', link: 'https://5jp1.github.io/theassets/ovo/', source: 'BetterMath' },
  { id: 'pandemic2', title: 'Pandemic 2', image: 'https://5jp1.github.io/theassets/pandemic2/pandemic2.png', link: 'https://5jp1.github.io/theassets/pandemic2/', source: 'BetterMath' },
  { id: 'papasburgeria', title: "Papa's Burgeria", image: 'https://5jp1.github.io/theassets/papasburgeria/splash.jpg', link: 'https://5jp1.github.io/theassets/papasburgeria/', source: 'BetterMath' },
  { id: 'papaspizzaria', title: "Papa's Pizzaria", image: 'https://5jp1.github.io/theassets/papaspizzaria/papaspizzaria.jpg', link: 'https://5jp1.github.io/theassets/papaspizzaria/', source: 'BetterMath' },
  { id: 'paperio2', title: 'Paper.io 2', image: 'https://5jp1.github.io/theassets/paperio2/images/icon512.png', link: 'https://5jp1.github.io/theassets/paperio2/', source: 'BetterMath' },
  { id: 'paperyplanes', title: 'Papery Planes', image: 'https://5jp1.github.io/theassets/papery-planes/splash.jpg', link: 'https://5jp1.github.io/theassets/papery-planes/', source: 'BetterMath' },
  { id: 'particleclicker', title: 'Particle Clicker', image: 'https://5jp1.github.io/theassets/particle-clicker/assets/mobile/original.png', link: 'https://5jp1.github.io/theassets/particle-clicker/', source: 'BetterMath' },
  { id: 'pixelgunsurvival', title: 'Pixel Gun Survival', image: 'https://5jp1.github.io/theassets/pixel-gun-survival/512x512.png', link: 'https://5jp1.github.io/theassets/pixel-gun-survival/', source: 'BetterMath' },
  { id: 'polybranch', title: 'PolyBranch', image: 'https://5jp1.github.io/theassets/polybranch/img/pic1.png', link: 'https://5jp1.github.io/theassets/polybranch/', source: 'BetterMath' },
  { id: 'popcatclassic', title: 'POPCAT CLASSIC', image: 'https://5jp1.github.io/theassets/popcat-classic/splash.png', link: 'https://5jp1.github.io/theassets/popcat-classic/', source: 'BetterMath' },
  { id: 'portalflash', title: 'Portal (Flash)', image: 'https://5jp1.github.io/theassets/portalflash/portaltheflashversion.jpg', link: 'https://5jp1.github.io/theassets/portalflash/', source: 'BetterMath' },
  { id: 'precisionclient', title: 'Precision Client (Eaglercraft)', image: 'https://5jp1.github.io/theassets/precision-client/logo.png', link: 'https://5jp1.github.io/theassets/precision-client/', source: 'BetterMath' },
  { id: 'protektor', title: 'Protektor', image: 'https://5jp1.github.io/theassets/protektor/splash.jpg', link: 'https://5jp1.github.io/theassets/protektor/', source: 'BetterMath' },
  { id: 'pushthesquare', title: 'Push The Square', image: 'https://5jp1.github.io/theassets/push-the-square/img/splash.png', link: 'https://5jp1.github.io/theassets/push-the-square/', source: 'BetterMath' },
  { id: 'pushyourluck', title: 'Push Your Luck', image: 'https://5jp1.github.io/theassets/push-your-luck/assets/img/push.png', link: 'https://5jp1.github.io/theassets/push-your-luck/', source: 'BetterMath' },
  { id: 'rabbitsamurai', title: 'Rabbit Samurai', image: 'https://5jp1.github.io/theassets/rabbit-samurai/splash.png', link: 'https://5jp1.github.io/theassets/rabbit-samurai/', source: 'BetterMath' },
  { id: 'rabbitsamurai2', title: 'Rabbit Samurai 2', image: 'https://5jp1.github.io/theassets/rabbit-samurai2/splash.png', link: 'https://5jp1.github.io/theassets/rabbit-samurai2/', source: 'BetterMath' },
  { id: 'resentclient', title: 'Resent Client (Eaglercraft)', image: 'https://5jp1.github.io/theassets/resent-client/splash.jpg', link: 'https://5jp1.github.io/theassets/resent-client/', source: 'BetterMath' },
  { id: 'retro-bowl', title: 'Retro Bowl', image: 'https://5jp1.github.io/theassets/retro-bowl/img/icon.jpg', link: 'https://5jp1.github.io/theassets/retro-bowl/', source: 'BetterMath' },
  { id: 'riddleschool1', title: 'Riddle School 1', image: 'https://5jp1.github.io/theassets/riddleschool/riddleschool.png', link: 'https://5jp1.github.io/theassets/riddleschool/', source: 'BetterMath' },
  { id: 'riddleschool2', title: 'Riddle School 2', image: 'https://5jp1.github.io/theassets/riddleschool2/riddleschool2.png', link: 'https://5jp1.github.io/theassets/riddleschool2/', source: 'BetterMath' },
  { id: 'riddleschool3', title: 'Riddle School 3', image: 'https://5jp1.github.io/theassets/riddleschool3/riddleschool3.png', link: 'https://5jp1.github.io/theassets/riddleschool3/', source: 'BetterMath' },
  { id: 'riddleschool4', title: 'Riddle School 4', image: 'https://5jp1.github.io/theassets/riddleschool4/riddleschool4.png', link: 'https://5jp1.github.io/theassets/riddleschool4/', source: 'BetterMath' },
  { id: 'riddleschool5', title: 'Riddle School 5', image: 'https://5jp1.github.io/theassets/riddleschool5/riddleschool5.png', link: 'https://5jp1.github.io/theassets/riddleschool5/', source: 'BetterMath' },
  { id: 'riddletransfer1', title: 'Riddle School Transfer 1', image: 'https://5jp1.github.io/theassets/riddletransfer/riddletransfer.png', link: 'https://5jp1.github.io/theassets/riddletransfer/', source: 'BetterMath' },
  { id: 'riddletransfer2', title: 'Riddle School Transfer 2', image: 'https://5jp1.github.io/theassets/riddletransfer2/riddletransfer2.png', link: 'https://5jp1.github.io/theassets/riddletransfer2/', source: 'BetterMath' },
  { id: 'rollingforests', title: 'Rolling Forests', image: 'https://5jp1.github.io/theassets/rolling-forests/icon.png', link: 'https://5jp1.github.io/theassets/rolling-forests/', source: 'BetterMath' },
  { id: 'rollyvortex', title: 'Rolly Vortex', image: 'https://5jp1.github.io/theassets/rolly-vortex/icon-256.png', link: 'https://5jp1.github.io/theassets/rolly-vortex/', source: 'BetterMath' },
  { id: 'rooftopsnipers', title: 'Rooftop Snipers', image: 'https://5jp1.github.io/theassets/rooftop-snipers/img/preview.png', link: 'https://5jp1.github.io/theassets/rooftop-snipers/', source: 'BetterMath' },
  { id: 'ruffle', title: 'Ruffle Emulator', image: 'https://5jp1.github.io/theassets/ruffle/splash.png', link: 'https://5jp1.github.io/theassets/ruffle/', source: 'BetterMath' },
  { id: 'sandboxels', title: 'Sandboxels', image: 'https://5jp1.github.io/theassets/sandboxels/sandboxels.jpg', link: 'https://5jp1.github.io/theassets/sandboxels/', source: 'BetterMath' },
  { id: 'santyishome', title: 'Santy is Home', image: 'https://5jp1.github.io/theassets/santy-is-home/splash.png', link: 'https://5jp1.github.io/theassets/santy-is-home/', source: 'BetterMath' },
  { id: 'sandgame', title: 'Sand Game', image: 'https://5jp1.github.io/theassets/sand-game/sand.png', link: 'https://5jp1.github.io/theassets/sand-game/', source: 'BetterMath' },
  { id: 'scrapmetal3', title: 'Scrap Metal 3', image: 'https://5jp1.github.io/theassets/scrapmetal/img/splash.png', link: 'https://5jp1.github.io/theassets/scrapmetal/', source: 'BetterMath' },
  { id: 'shellshockers', title: 'Shellshockers', image: 'https://5jp1.github.io/theassets/shellshockers/img/favicon.jpg', link: 'https://5jp1.github.io/theassets/shellshockers/', source: 'BetterMath' },
  { id: 'shotinthedark', title: 'Shot in the Dark', image: 'https://5jp1.github.io/theassets/shotinthedark/shot.png', link: 'https://5jp1.github.io/theassets/shotinthedark/', source: 'BetterMath' },
  { id: 'shuttledeck', title: 'SHUTTLEDECK', image: 'https://5jp1.github.io/theassets/shuttledeck/splash.png', link: 'https://5jp1.github.io/theassets/shuttledeck/', source: 'BetterMath' },
  { id: 'skycarstunt', title: 'Sky Car Stunt', image: 'https://5jp1.github.io/theassets/sky-car-stunt/512x512.jpg', link: 'https://5jp1.github.io/theassets/sky-car-stunt/', source: 'BetterMath' },
  { id: 'sleepingbeauty', title: 'Sleeping Beauty', image: 'https://5jp1.github.io/theassets/sleepingbeauty/splash.png', link: 'https://5jp1.github.io/theassets/sleepingbeauty/', source: 'BetterMath' },
  { id: 'slimerushtd', title: 'Slime Rush TD', image: 'https://5jp1.github.io/theassets/slime-rush-td/splash.png', link: 'https://5jp1.github.io/theassets/slime-rush-td/', source: 'BetterMath' },
  { id: 'slope', title: 'Slope', image: 'https://5jp1.github.io/theassets/slope/slope4.jpeg', link: 'https://5jp1.github.io/theassets/slope/', source: 'BetterMath' },
  { id: 'slope-2', title: 'Slope 2', image: 'https://5jp1.github.io/theassets/slope-2/slope-2-logo.png', link: 'https://5jp1.github.io/theassets/slope-2/', source: 'BetterMath' },
  { id: 'slope-3', title: 'Slope 3', image: 'https://tse1.mm.bing.net/th/id/OIP._RQtj6IWQS-G6wR_Xe4vzAAAAA?rs=1&pid=ImgDetMain&o=7&rm=3', link: 'https://5jp1.github.io/slope3', source: 'BetterMath' },
  { id: 'slopeball', title: 'Slope Ball', image: 'https://5jp1.github.io/theassets/slope-ball/splash.png', link: 'https://5jp1.github.io/theassets/slope-ball/', source: 'BetterMath' },
  { id: 'sm64', title: 'Super Mario 64', image: 'https://5jp1.github.io/theassets/sm64/logo.png', link: 'https://5jp1.github.io/theassets/sm64/', source: 'BetterMath' },
  { id: 'smashcarts', title: 'Smash Carts', image: 'https://5jp1.github.io/theassets/smashkarts/images/icon-512.png', link: 'https://5jp1.github.io/theassets/smashkarts/', source: 'BetterMath' },
  { id: 'smokingbarrels', title: 'Smoking Barrels', image: 'https://5jp1.github.io/theassets/smokingbarrels/smokingbarrels.jpg', link: 'https://5jp1.github.io/theassets/smokingbarrels/', source: 'BetterMath' },
  { id: 'snowbattle', title: 'Snowbattle', image: 'https://5jp1.github.io/theassets/snowbattle/img/logo.png', link: 'https://5jp1.github.io/theassets/snowbattle/', source: 'BetterMath' },
  { id: 'soccerrandom', title: 'Soccer Random', image: 'https://5jp1.github.io/theassets/soccer-random/unnamed.png', link: 'https://5jp1.github.io/theassets/soccer-random/', source: 'BetterMath' },
  { id: 'soccerskillseuro', title: 'Soccer Skills Euro Cup', image: 'https://5jp1.github.io/theassets/soccer-skills/splash.png', link: 'https://5jp1.github.io/theassets/soccer-skills/', source: 'BetterMath' },
  { id: 'soldierlegend', title: 'Soilder Legend', image: 'https://5jp1.github.io/theassets/soldier-legend/images/splash.jpeg', link: 'https://5jp1.github.io/theassets/soldier-legend/', source: 'BetterMath' },
  { id: 'solitaire', title: 'Solitare', image: 'https://5jp1.github.io/theassets/solitaire/screen-shot.png', link: 'https://5jp1.github.io/theassets/solitaire/', source: 'BetterMath' },
  { id: 'sortthecourt', title: 'Sort The Court', image: 'https://5jp1.github.io/theassets/sort-the-court/img/splash.png', link: 'https://5jp1.github.io/theassets/sort-the-court/', source: 'BetterMath' },
  { id: 'soundboard', title: 'Soundboard', image: 'https://5jp1.github.io/theassets/soundboard/img/mlg-favicon.png', link: 'https://5jp1.github.io/soundboard', source: 'BetterMath' },
  { id: 'spacecompany', title: 'Space Company', image: 'https://5jp1.github.io/theassets/space-company/Icons/SpaceCompanyFavicon.png', link: 'https://5jp1.github.io/theassets/space-company/', source: 'BetterMath' },
  { id: 'spacegarden', title: 'Space Garden', image: 'https://5jp1.github.io/theassets/spacegarden/spl.png', link: 'https://5jp1.github.io/theassets/spacegarden/', source: 'BetterMath' },
  { id: 'spinningrat', title: 'Spinning Rat', image: 'https://5jp1.github.io/theassets/spinningrat/apple-touch-icon.png', link: 'https://5jp1.github.io/theassets/spinningrat/', source: 'BetterMath' },
  { id: 'stack', title: 'Stack', image: 'https://5jp1.github.io/theassets/stack/stack.png', link: 'https://5jp1.github.io/theassets/stack/', source: 'BetterMath' },
  { id: 'stackbump3d', title: 'Stack Bump 3D', image: 'https://5jp1.github.io/theassets/stack-bump-3d/thumbnail.jpg', link: 'https://5jp1.github.io/theassets/stack-bump-3d/', source: 'BetterMath' },
  { id: 'starveio', title: 'Starve.io', image: 'https://5jp1.github.io/theassets/starve/img/favicon.png', link: 'https://5jp1.github.io/theassets/starve/', source: 'BetterMath' },
  { id: 'station141', title: 'Station 141', image: 'https://5jp1.github.io/theassets/station-141/75wxYs.png', link: 'https://5jp1.github.io/theassets/station-141/', source: 'BetterMath' },
  { id: 'stealingthediamond', title: 'Stealing The Diamond', image: 'https://5jp1.github.io/theassets/stealingthediamond/stealingthediamond.jpg', link: 'https://5jp1.github.io/theassets/stealingthediamond/', source: 'BetterMath' },
  { id: 'stickarchers', title: 'Stick Archers', image: 'https://5jp1.github.io/theassets/stick-archers/splash.jpg', link: 'https://5jp1.github.io/theassets/stick-archers/', source: 'BetterMath' },
  { id: 'stickduelbattle', title: 'Stick Duel Battle', image: 'https://5jp1.github.io/theassets/stick-duel-battle/512x512.jpg', link: 'https://5jp1.github.io/theassets/stick-duel-battle/', source: 'BetterMath' },
  { id: 'stickmerge', title: 'Stick Merge', image: 'https://5jp1.github.io/theassets/stick-merge/splash.png', link: 'https://5jp1.github.io/theassets/stick-merge/', source: 'BetterMath' },
  { id: 'stickmanboost', title: 'Stickman Boost', image: 'https://5jp1.github.io/theassets/stickman-boost/base/img1.jpg', link: 'https://5jp1.github.io/theassets/stickman-boost/', source: 'BetterMath' },
  { id: 'stickmangolf', title: 'Stickman Golf', image: 'https://5jp1.github.io/theassets/stickman-golf/splash.png', link: 'https://5jp1.github.io/theassets/stickman-golf/', source: 'BetterMath' },
  { id: 'stickmanhook', title: 'Stickman Hook', image: 'https://5jp1.github.io/theassets/stickman-hook/unnamed.jpg', link: 'https://5jp1.github.io/theassets/stickman-hook/', source: 'BetterMath' },
  { id: 'stickmansurvival', title: 'Stickman Survival', image: 'https://5jp1.github.io/theassets/Stickman-Survival/Icon.png', link: 'https://5jp1.github.io/theassets/stickman-survival/', source: 'BetterMath' },
  { id: 'stickwar', title: 'Stick War', image: 'https://5jp1.github.io/theassets/stickwar/stickwar.jpg', link: 'https://5jp1.github.io/theassets/stickwar/', source: 'BetterMath' },
  { id: 'stormthehouse2', title: 'Storm The House 2', image: 'https://5jp1.github.io/theassets/stormthehouse2/stormthehouse2.jpg', link: 'https://5jp1.github.io/theassets/stormthehouse2/', source: 'BetterMath' },
  { id: 'subwaysurfers', title: 'Subway Surfers', image: 'https://5jp1.github.io/theassets/subway-surfers/img/splash.jpg', link: 'https://5jp1.github.io/theassets/subway-surfers/', source: 'BetterMath' },
  { id: 'subwaysurfersny', title: 'Subway Surfers New York', image: 'https://5jp1.github.io/theassets/subway-surfers-ny/NewYorkIcon.png', link: 'https://5jp1.github.io/theassets/subway-surfers-ny/', source: 'BetterMath' },
  { id: 'superhot', title: 'Superhot', image: 'https://5jp1.github.io/theassets/superhot/hot.jpg', link: 'https://5jp1.github.io/theassets/superhot/', source: 'BetterMath' },
  { id: 'supermarioconstruct', title: 'Super Mario Constuct', image: 'https://5jp1.github.io/theassets/supermarioconstruct/media/icons/icon-128.png', link: 'https://5jp1.github.io/theassets/supermarioconstruct/', source: 'BetterMath' },
  { id: 'survivio', title: 'Surviv.io', image: 'https://5jp1.github.io/theassets/surviv/img/favicon.png', link: 'https://5jp1.github.io/theassets/surviv/', source: 'BetterMath' },
  { id: 'sushiunroll', title: 'Sushi unROLL', image: 'https://5jp1.github.io/theassets/sushi-unroll/favicon.png', link: 'https://5jp1.github.io/theassets/sushi-unroll/', source: 'BetterMath' },
  { id: 'swerve', title: 'Swerve', image: 'https://5jp1.github.io/theassets/swerve/img/favicon.jpg', link: 'https://5jp1.github.io/theassets/swerve/', source: 'BetterMath' },
  { id: 'synesthesia', title: 'Synesthesia', image: 'https://5jp1.github.io/theassets/synesthesia/index.splash.png', link: 'https://5jp1.github.io/theassets/synesthesia/', source: 'BetterMath' },
  { id: 'tacticalweaponpack2', title: 'Tactical Weapon Pack 2', image: 'https://5jp1.github.io/theassets/tactical-weapon-pack-2/splash.jpg', link: 'https://5jp1.github.io/theassets/tactical-weapon-pack-2/', source: 'BetterMath' },
  { id: 'tacticalassassin2', title: 'Tactical Assassin 2', image: 'https://5jp1.github.io/theassets/tacticalassasin2/tacticalassassin2.png', link: 'https://5jp1.github.io/theassets/tacticalassasin2/', source: 'BetterMath' },
  { id: 'tanktrouble2', title: 'Tank Trouble 2', image: 'https://5jp1.github.io/theassets/tank-trouble-2/tank.jpeg', link: 'https://5jp1.github.io/theassets/tank-trouble-2/', source: 'BetterMath' },
  { id: 'tanukisunset', title: 'Tanuki Sunset', image: 'https://5jp1.github.io/theassets/tanuki-sunset/img/cover.png', link: 'https://5jp1.github.io/theassets/tanuki-sunset/', source: 'BetterMath' },
  { id: 'templerun2', title: 'Temple Run 2', image: 'https://5jp1.github.io/theassets/temple-run-2/img/og-icon.png', link: 'https://5jp1.github.io/theassets/temple-run-2/', source: 'BetterMath' },
  { id: 'thebattle', title: 'The Battle', image: 'https://5jp1.github.io/theassets/thebattle/thebattle.png', link: 'https://5jp1.github.io/theassets/thebattle/', source: 'BetterMath' },
  { id: 'finalearth', title: 'The Final Earth', image: 'https://5jp1.github.io/theassets/the-final-earth/images.png', link: 'https://5jp1.github.io/theassets/the-final-earth/', source: 'BetterMath' },
  { id: 'thehotel', title: 'The Hotel', image: 'https://5jp1.github.io/theassets/the-hotel/splash.png', link: 'https://5jp1.github.io/theassets/the-hotel/', source: 'BetterMath' },
  { id: 'theheist', title: 'The Heist', image: 'https://5jp1.github.io/theassets/theheist/theheist.jpg', link: 'https://5jp1.github.io/theassets/theheist/', source: 'BetterMath' },
  { id: 'thereisnogame', title: 'There Is No Game', image: 'https://5jp1.github.io/theassets/there-is-no-game/logo.png', link: 'https://5jp1.github.io/theassets/there-is-no-game/', source: 'BetterMath' },
  { id: 'onlylevel', title: 'This Is The Only Level', image: 'https://5jp1.github.io/theassets/thisistheonlylevel/thisistheonlylevel.png', link: 'https://5jp1.github.io/theassets/thisistheonlylevel/', source: 'BetterMath' },
  { id: 'tinyfishing', title: 'Tiny Fishing', image: 'https://5jp1.github.io/theassets/tiny-fishing/thumb.png', link: 'https://5jp1.github.io/theassets/tiny-fishing/', source: 'BetterMath' },
  { id: 'tinyislands', title: 'Tiny Islands', image: 'https://5jp1.github.io/theassets/tiny-islands/splash.png', link: 'https://5jp1.github.io/theassets/tiny-islands/', source: 'BetterMath' },
  { id: 'tosstheturtle', title: 'Toss The Turtle', image: 'https://5jp1.github.io/theassets/tosstheturtle/tosstheturtle.png', link: 'https://5jp1.github.io/theassets/tosstheturtle/', source: 'BetterMath' },
  { id: 'townscaper', title: 'Townscaper', image: 'https://5jp1.github.io/theassets/townscaper/img/cover.jpg', link: 'https://5jp1.github.io/theassets/townscaper/', source: 'BetterMath' },
  { id: 'tubejumpers', title: 'Tube Jumpers', image: 'https://5jp1.github.io/theassets/tube-jumpers/img/shark.jpg', link: 'https://5jp1.github.io/theassets/tube-jumpers/', source: 'BetterMath' },
  { id: 'tunnelrush', title: 'Tunnel Rush', image: 'https://5jp1.github.io/theassets/tunnel-rush/img/tunnel.jpg', link: 'https://5jp1.github.io/theassets/tunnel-rush/', source: 'BetterMath' },
  { id: 'tvstatic', title: 'TV Static', image: 'https://5jp1.github.io/theassets/tv-static/static.png', link: 'https://5jp1.github.io/theassets/tv-static/', source: 'BetterMath' },
  { id: 'twitchtetris', title: 'Twitch Tetris', image: 'https://5jp1.github.io/theassets/twitch-tetris/logo.png', link: 'https://5jp1.github.io/theassets/twitch-tetris/', source: 'BetterMath' },
  { id: 'veloce', title: 'VELOCE', image: 'https://5jp1.github.io/theassets/veloce/qN6zkD.png', link: 'https://5jp1.github.io/theassets/veloce/', source: 'BetterMath' },
  { id: 'vex3', title: 'Vex 3', image: 'https://5jp1.github.io/theassets/vex3/vex3.png', link: 'https://5jp1.github.io/theassets/vex3/', source: 'BetterMath' },
  { id: 'vex4', title: 'Vex 4', image: 'https://5jp1.github.io/theassets/vex4/vex4.png', link: 'https://5jp1.github.io/theassets/vex4/', source: 'BetterMath' },
  { id: 'vex5', title: 'Vex 5', image: 'https://5jp1.github.io/theassets/vex5/vex.jpeg', link: 'https://5jp1.github.io/theassets/vex5/', source: 'BetterMath' },
  { id: 'vex6', title: 'Vex 6', image: 'https://5jp1.github.io/theassets/vex6/assets/icon.jpeg', link: 'https://5jp1.github.io/theassets/vex6/', source: 'BetterMath' },
  { id: 'vex7', title: 'Vex 7', image: 'https://5jp1.github.io/theassets/vex7/assets/icon.jpeg', link: 'https://5jp1.github.io/theassets/vex7/', source: 'BetterMath' },
  { id: 'waterworks', title: 'Waterworks!', image: 'https://5jp1.github.io/theassets/waterworks/square.png', link: 'https://5jp1.github.io/theassets/waterworks/', source: 'BetterMath' },
  { id: 'wallsmash', title: 'Wall Smash', image: 'https://5jp1.github.io/theassets/wallsmash/thumb.png', link: 'https://5jp1.github.io/theassets/wallsmash/', source: 'BetterMath' },
  { id: 'weavesilk', title: 'Weave Silk', image: 'https://5jp1.github.io/theassets/weavesilk/thumb.png', link: 'https://5jp1.github.io/theassets/weavesilk/', source: 'BetterMath' },
  { id: 'webglfluid', title: 'WebGL Fluid Sim', image: 'https://5jp1.github.io/theassets/webgl-fluid-simulation/logo.png', link: 'https://5jp1.github.io/theassets/webgl-fluid-simulation/', source: 'BetterMath' },
  { id: 'webretro', title: 'Webretro', image: 'https://5jp1.github.io/theassets/webretro/assets/icons/icon204.png', link: 'https://5jp1.github.io/theassets/webretro/roms', source: 'BetterMath' },
  { id: 'whitehouse', title: 'Win the Whitehouse', image: 'https://5jp1.github.io/theassets/win-the-whitehouse/splash.png', link: 'https://5jp1.github.io/theassets/win-the-whitehouse/', source: 'BetterMath' },
  { id: 'wolf3d', title: 'Wolfenstein 3D', image: 'https://5jp1.github.io/theassets/wolf3d/art/wolf3d.png', link: 'https://5jp1.github.io/theassets/wolf3d/', source: 'BetterMath' },
  { id: 'wordle', title: 'Wordle', image: 'https://5jp1.github.io/theassets/wordle/img/logo_512x512.png', link: 'https://5jp1.github.io/theassets/wordle/', source: 'BetterMath' },
  { id: 'hardestgame', title: "World's Hardest Game", image: 'https://5jp1.github.io/theassets/worlds-hardest-game/images/splash.jpg', link: 'https://5jp1.github.io/theassets/worlds-hardest-game/', source: 'BetterMath' },
  { id: 'hardestgame2', title: "World's Hardest Game 2", image: 'https://5jp1.github.io/theassets/worlds-hardest-game-2/the-worlds-hardest-game-2.jpg', link: 'https://5jp1.github.io/theassets/worlds-hardest-game-2/', source: 'BetterMath' },
  { id: 'xtrialracing', title: 'X Trial Racing', image: 'https://5jp1.github.io/theassets/x-trial-racing/splash.png', link: 'https://5jp1.github.io/theassets/x-trial-racing/', source: 'BetterMath' },
  { id: 'xx142b2exe', title: 'xx142-b2exe', image: 'https://5jp1.github.io/theassets/xx142-b2exe/splash.png', link: 'https://5jp1.github.io/theassets/xx142-b2exe/', source: 'BetterMath' },
  { id: 'yoshifab', title: "Yoshi's Fabrication Station", image: 'https://5jp1.github.io/theassets/yoshifabrication/icons/icon-512.png', link: 'https://5jp1.github.io/theassets/yoshifabrication/', source: 'BetterMath' },
  { id: 'bezos', title: 'You Are Jeff Bezos', image: 'https://5jp1.github.io/theassets/you-are-bezos/img/banner.png', link: 'https://5jp1.github.io/theassets/you-are-bezos/', source: 'BetterMath' },
  { id: 'zombsroyale', title: 'Zombs Royale', image: 'https://5jp1.github.io/theassets/zombs-royale/zomb.png', link: 'https://5jp1.github.io/theassets/zombs-royale/', source: 'BetterMath' }
];

export const INITIAL_PLUGPLAY_GAMES: Game[] = [
  { id: 'pp-vex4', title: 'Vex 4: Ultimate Stickman Challenge', image: 'https://plugplay.games/data/uploads/img_6835d679d7fee.jpeg', link: 'https://plugplay.games/embed/5920d6a30e37dc108056faf538325ff4b51f56d8', source: 'PlugPlay' },
  { id: 'pp-vex3', title: 'Vex 3: Ultimate Stickman Challenge', image: 'https://plugplay.games/data/uploads/img_6835d651513d6.png', link: 'https://plugplay.games/embed/fbe897886f7ee30addc1ee3d1e6215ba7754a71f', source: 'PlugPlay' },
  { id: 'pp-tiny-fishing', title: 'Pocket Angler: Tiny Fishing Adventure', image: 'https://plugplay.games/data/uploads/img_6835d5c351692.png', link: 'https://plugplay.games/embed/07a82656316484493b52e8f31fc2f5a3c987b3e0', source: 'PlugPlay' },
  { id: 'pp-subway-surfers', title: 'Subway Surfers: Singapore Dash', image: 'https://plugplay.games/data/uploads/img_6835d580e72e8.png', link: 'https://plugplay.games/embed/aae25d4cf623e6da948e59855238b6a4053e5846', source: 'PlugPlay' },
  { id: 'pp-nyc-subway', title: 'NYC Subway Rush: Endless Runner Adventure', image: 'https://plugplay.games/data/uploads/img_6835d560a4547.png', link: 'https://plugplay.games/embed/a228e05e0afee175ca33adc31f52ef6e04ad83e2', source: 'PlugPlay' },
  { id: 'pp-stickman-hook', title: 'Stickman Hook: Swing Master', image: 'https://plugplay.games/data/uploads/img_6835d53a98207.jpg', link: 'https://plugplay.games/embed/1c61b71c9b4302faf505bd65ab92291a1ec7655c', source: 'PlugPlay' },
  { id: 'pp-snow-warrior', title: 'Snow Warrior: Epic Winter Battle', image: 'https://plugplay.games/data/uploads/img_6835d3e9ccb29.png', link: 'https://plugplay.games/embed/04792e5a4a36d9d79eb2503489b3f4935a3f582e', source: 'PlugPlay' },
  { id: 'pp-cosmic-rescuers', title: 'Cosmic Rescuers: Packabunchas', image: 'https://plugplay.games/data/uploads/img_6835d306b735a.png', link: 'https://plugplay.games/embed/1aabdbffc6272e9832cab5e9fb05aa7ab711b122', source: 'PlugPlay' },
  { id: 'pp-moto-rash', title: 'Speed Demons: Moto Road Rash 3D', image: 'https://plugplay.games/data/uploads/img_6835d2a122583.png', link: 'https://plugplay.games/embed/e6f25b439e06e4789a3062f1c322bbec3482ede7', source: 'PlugPlay' },
  { id: 'pp-monkey-mart', title: 'Banana Bonanza: Monkey Mart Manager', image: 'https://plugplay.games/data/uploads/img_6835d27345d75.png', link: 'https://plugplay.games/embed/afa25719b9689d8e515fd4c5cd26ae58709c8a16', source: 'PlugPlay' },
  { id: 'pp-wave-rider', title: 'Wave Rider: Ultimate Surf Challenge', image: 'https://plugplay.games/data/uploads/img_6835d231a2d48.png', link: 'https://plugplay.games/embed/98fb34f34331bc455cbbe1a04bd22b392c7f5160', source: 'PlugPlay' },
  { id: 'pp-turbo-gopher', title: 'Turbo Gopher Racing', image: 'https://plugplay.games/data/uploads/img_6835d1da40d36.png', link: 'https://plugplay.games/embed/266af8b07cccd8b4a4433633ab8af97fd13ca900', source: 'PlugPlay' },
  { id: 'pp-gladihoppers', title: 'Gladihoppers: Arena Warriors', image: 'https://plugplay.games/data/uploads/img_6835d126cf7b0.png', link: 'https://plugplay.games/embed/8353e9c8c7327dea3332c707574eede6cbf27d76', source: 'PlugPlay' },
  { id: 'pp-zombie-crusher', title: 'Zombie Crusher: Apocalypse Driver', image: 'https://plugplay.games/data/uploads/img_6835d07b4f2c1.png', link: 'https://plugplay.games/embed/c66b3b31090c007ab12ddabd472350186d7a2e99', source: 'PlugPlay' },
  { id: 'pp-drive-mad', title: 'Drive Mad: Extreme Physics Racer', image: 'https://plugplay.games/data/uploads/img_6835d044297c5.jpg', link: 'https://plugplay.games/embed/73e6c7bc9aa81a4abfd34a0a3df36aaf923a5cf6', source: 'PlugPlay' },
  { id: 'pp-drift-masters', title: 'Drift Masters: Ultimate Racing Challenge', image: 'https://plugplay.games/data/uploads/img_6835d02caea4f.png', link: 'https://plugplay.games/embed/3339796ef6a704b2b21dd3c07c6cef9b49eb2874', source: 'PlugPlay' },
  { id: 'pp-holiday-rope', title: "Holiday Rope Cutter: Om Nom's Festive Adventure", image: 'https://plugplay.games/data/uploads/img_6835cfcd0f5e1.png', link: 'https://plugplay.games/embed/505389e7fb4cf73a08021b5db311e6d1804f8f8a', source: 'PlugPlay' },
  { id: 'pp-bounce-master', title: 'Bounce Master: Gravity Challenge', image: 'https://plugplay.games/data/uploads/img_6835cefadfe42.png', link: 'https://plugplay.games/embed/39d0a0985116974105a93c5cfbdcaa3a8152bb40', source: 'PlugPlay' },
  { id: 'pp-basket-chaos', title: 'Basket Chaos: Random Hoops', image: 'https://plugplay.games/data/uploads/img_6835ce8ac2a3c.png', link: 'https://plugplay.games/embed/8858d9cf31f8dd0e94fc385cc92dff10f05d6a64', source: 'PlugPlay' },
  { id: 'pp-basket-bros', title: 'Basket Bros.io: Slam Dunk Showdown', image: 'https://plugplay.games/data/uploads/img_6835ce5f22f12.jpg', link: 'https://plugplay.games/embed/b10a19f82d47697b8f572088740665678cbd1346', source: 'PlugPlay' },
  { id: 'pp-basketball-stars', title: 'Basketball Stars: Street Hoops Challenge', image: 'https://plugplay.games/data/uploads/img_6835ce3679c57.png', link: 'https://plugplay.games/embed/b250ef3373e504b21e1044896de624c77bb2cf87', source: 'PlugPlay' },
  { id: 'pp-baldis-basics', title: "Baldi's Basics: Educational Horror Challenge", image: 'https://plugplay.games/data/uploads/img_6835ce19b0e50.png', link: 'https://plugplay.games/embed/9c79ba8f01156e8cf14cbec36163f6e04b7fba91', source: 'PlugPlay' },
  { id: 'pp-backcountry-rush', title: 'Backcountry Powder Rush', image: 'https://plugplay.games/data/uploads/img_6835cde237391.png', link: 'https://plugplay.games/embed/f031e7b50d180af132787f9a6f67e84e7184822a', source: 'PlugPlay' },
  { id: 'pp-numberfly', title: 'NumberFly 2048: Flap & Merge', image: 'https://plugplay.games/data/uploads/img_6835cd6e91468.png', link: 'https://plugplay.games/embed/f40d75cce29837f6b4d964a81df32413f67cfe39', source: 'PlugPlay' },
  { id: 'pp-hexgl', title: 'HexGL: Hyperspeed Fusion Racer', image: 'https://plugplay.games/data/uploads/img_6835cced0c51a.png', link: 'https://plugplay.games/embed/cf980f7e2c7f68297ea902d36ad984e4cdfe7802', source: 'PlugPlay' },
  { id: 'pp-blockstack', title: 'BlockStack Blitz', image: 'https://plugplay.games/data/uploads/img_6835ccbbc3a57.png', link: 'https://plugplay.games/embed/419ce6e7690abe4d9ebacb5f027d163c86bef0c8', source: 'PlugPlay' },
  { id: 'pp-paper-warriors', title: 'Territory Conquest: Paper Warriors', image: 'https://plugplay.games/data/uploads/img_6835cc5a38931.png', link: 'https://plugplay.games/embed/1a0df80c67bc42297fcb4211a8160c1aee020312', source: 'PlugPlay' },
  { id: 'pp-lifecraft', title: 'LifeCraft: Ultimate Destiny Simulator', image: 'https://plugplay.games/data/uploads/img_6835befde3b49.png', link: 'https://plugplay.games/embed/ea68b18af181801818abf03713c82c634b60a0b9', source: 'PlugPlay' },
  { id: 'pp-brick-blitz', title: 'Brick Blitz: Ultimate Breakout', image: 'https://plugplay.games/data/uploads/img_6835beb77170b.jpg', link: 'https://plugplay.games/embed/60d1e9c65670a1ad2a71efa0df7b4a5583f9518c', source: 'PlugPlay' },
  { id: 'pp-basketball-legends', title: 'Basketball Legends: Slam Dunk Champions', image: 'https://plugplay.games/data/uploads/img_6835be81c7db9.png', link: 'https://plugplay.games/embed/407d50478f182513b4f797c37b6f7bbead2b16df', source: 'PlugPlay' },
  { id: 'pp-maze-runner', title: 'Maze Runner 3D: Astray Challenge', image: 'https://plugplay.games/data/uploads/img_6835be6726269.png', link: 'https://plugplay.games/embed/1f999c5d6c2fdd5630d951c9a21dbaafa60367e7', source: 'PlugPlay' },
  { id: 'pp-mindscan', title: 'MindScan: Psychological Horror Test', image: 'https://plugplay.games/data/uploads/img_6835be3908e04.png', link: 'https://plugplay.games/embed/00891f888eb4cb0c0f391adf9cc8f42ab613a5a7', source: 'PlugPlay' },
  { id: 'pp-buildshoot', title: 'BuildShoot Arena: 1v1 Battle Royale', image: 'https://plugplay.games/data/uploads/img_6835be122d66d.png', link: 'https://plugplay.games/embed/9473f3a6113ce78538948d45eb39546ce8205af9', source: 'PlugPlay' },
  { id: 'pp-embers-awakening', title: "Ember's Awakening: A Dark Room", image: 'https://plugplay.games/data/uploads/img_6835bdfb2a105.png', link: 'https://plugplay.games/embed/3718473f4982ae9427b57f242826ba6e607d864d', source: 'PlugPlay' },
  { id: 'pp-numbermerge-puzzle', title: 'NumberMerge 2048: Puzzle Challenge', image: 'https://plugplay.games/data/uploads/img_6835bde0342bc.png', link: 'https://plugplay.games/embed/60798d0d8baf52dbfe806ffd1e61a4d5aa68fdcc', source: 'PlugPlay' },
  { id: 'pp-royal-checkmate', title: 'Royal Checkmate: Ultimate Chess Challenge', image: 'https://plugplay.games/data/uploads/img_6835bdc9c75fd.webp', link: 'https://plugplay.games/embed/6419815584676f60d90231df48c5c509da46544c', source: 'PlugPlay' },
  { id: 'pp-bubble-shooter', title: 'Bubble Shooter', image: 'https://plugplay.games/data/uploads/img_683090a5581ef.png', link: 'https://plugplay.games/embed/181a5a0d61b2889414e125874878b9989c724a8b', source: 'PlugPlay' },
  { id: 'pp-cosmic-defender-alien', title: 'Cosmic Defender: Alien Galaxy War', image: 'https://plugplay.games/data/uploads/img_68308bd4e9917.png', link: 'https://plugplay.games/embed/c13cd7447b278a4e2a3056aa578d6471662b9e21', source: 'PlugPlay' },
  { id: 'pp-undead-assault', title: 'Undead Assault: Zombie Apocalypse', image: 'https://plugplay.games/data/uploads/img_68307529900bb.png', link: 'https://plugplay.games/embed/67bad534a967e4b6ca42e75a9d32cdd4f70d67c1', source: 'PlugPlay' },
  { id: 'pp-wordmaster', title: 'WordMaster Challenge', image: 'https://plugplay.games/data/uploads/img_6830750c7383b.jpg', link: 'https://plugplay.games/embed/887c96ae3b4c769db6af7e7fc8ed1442b8fa9ba5', source: 'PlugPlay' },
  { id: 'pp-mystic-orbs', title: "Mystic Orbs: The Sorcerer's Challenge", image: 'https://plugplay.games/data/uploads/img_683074ef33724.jpg', link: 'https://plugplay.games/embed/3a0b494344cf097d0bd2742297e26402069e0991', source: 'PlugPlay' },
  { id: 'pp-nest-defender', title: 'Nest Defender: Bird Rescue Mission', image: 'https://plugplay.games/data/uploads/img_683074d7d3a5b.png', link: 'https://plugplay.games/embed/85f4a1f64e57de635ff453c9fc3e13ab24b0dd05', source: 'PlugPlay' },
  { id: 'pp-sweet-tile', title: 'Sweet Tile Crush: Candy Mahjong Adventure', image: 'https://plugplay.games/data/uploads/img_683074ba24e9c.jpg', link: 'https://plugplay.games/embed/cdd60e8db0666a939601299c790cddace0e5afa8', source: 'PlugPlay' },
  { id: 'pp-brain-master', title: 'Brain Master: Ultimate Sudoku Challenge', image: 'https://plugplay.games/data/uploads/img_68307497b0010.png', link: 'https://plugplay.games/embed/e5bcb73d105751b023192d8642184fb5e0ee001b', source: 'PlugPlay' },
  { id: 'pp-spectrum-dash', title: 'Spectrum Dash', image: 'https://plugplay.games/data/uploads/img_683074804869b.png', link: 'https://plugplay.games/embed/3e60932d0fe05af59e98a71392934fcaec7bcfaa', source: 'PlugPlay' },
  { id: 'pp-cosmic-defender-space', title: 'Cosmic Defender: Space Assault', image: 'https://plugplay.games/data/uploads/img_6830744d5e74b.png', link: 'https://plugplay.games/embed/1cbd4486a183ca88220b15b855061a48a13f071f', source: 'PlugPlay' },
  { id: 'pp-alpine-rush', title: 'Alpine Rush: Extreme Ski Challenge', image: 'https://plugplay.games/data/uploads/img_683074062c0b7.png', link: 'https://plugplay.games/embed/a84c23bd67f6064b6e1eccbd1a7066b62ba43b37', source: 'PlugPlay' },
  { id: 'pp-brain-twist', title: 'BrainTwist Puzzlers', image: 'https://plugplay.games/data/uploads/img_683073aaa27e5.jpg', link: 'https://plugplay.games/embed/b6bd6280a6ab0d0d7a7ce20ba4da6e48fb8e8839', source: 'PlugPlay' },
  { id: 'pp-animal-block', title: 'Animal Block Puzzle Mania', image: 'https://plugplay.games/data/uploads/img_68307396796ff.png', link: 'https://plugplay.games/embed/c9ea98c2a1c30f2960f7e2b5b095e94a6e193f4c', source: 'PlugPlay' },
  { id: 'pp-professor-bubble', title: 'Professor Bubble: Color Blast Adventure', image: 'https://plugplay.games/data/uploads/img_6830738211b57.png', link: 'https://plugplay.games/embed/309d8393127e8f6ad69fd1a385d62e6b73f0b490', source: 'PlugPlay' },
  { id: 'pp-pizza-party', title: 'Pizza Party Frenzy', image: 'https://plugplay.games/data/uploads/img_6830736ea1f86.png', link: 'https://plugplay.games/embed/b7abb1329e396872eb4ebd254d02f0309e347f23', source: 'PlugPlay' },
  { id: 'pp-pirate-treasure', title: "Pirate's Treasure Quest", image: 'https://plugplay.games/data/uploads/img_6830734c277ce.jpg', link: 'https://plugplay.games/embed/fb06e4357aabf568722a6b3e1a8cfbfa955b44e0', source: 'PlugPlay' },
  { id: 'pp-maze-muncher', title: 'Maze Muncher: Pac-Maker Adventure', image: 'https://plugplay.games/data/uploads/img_68307336e4a8a.png', link: 'https://plugplay.games/embed/61d80de57f224203444eae301720aa543136ee26', source: 'PlugPlay' },
  { id: 'pp-neon-rush', title: 'Neon Rush: Glow Runner', image: 'https://plugplay.games/data/uploads/img_6830731760136.png', link: 'https://plugplay.games/embed/f6314bbcc94e662eb29baf50dfb8786359dcb712', source: 'PlugPlay' },
  { id: 'pp-monster-munch', title: 'Monster Munch Mania', image: 'https://plugplay.games/data/uploads/img_683073004a60b.png', link: 'https://plugplay.games/embed/ba94124111009bf9b98225d65f3c059f58ad7cea', source: 'PlugPlay' },
  { id: 'pp-banana-bounce', title: 'Banana Bounce Adventure', image: 'https://plugplay.games/data/uploads/img_683072ee20db4.png', link: 'https://plugplay.games/embed/a94013b5e29e4df7b77cafc784ec99efe33a3162', source: 'PlugPlay' },
  { id: 'pp-pocket-putt', title: 'Pocket Putt Master', image: 'https://plugplay.games/data/uploads/img_683072d477411.jpg', link: 'https://plugplay.games/embed/8d3e14f36944b43ea853bbce87dad5a41e7ed99f', source: 'PlugPlay' },
  { id: 'pp-gold-rush', title: 'Gold Rush Escape: Mine Cart Puzzle', image: 'https://plugplay.games/data/uploads/img_683072ad601a4.jpg', link: 'https://plugplay.games/embed/4a5647e13bbb20a8dcbdff6f03f452b063fe607d', source: 'PlugPlay' },
  { id: 'pp-memorymaster', title: 'MemoryMaster Challenge', image: 'https://plugplay.games/data/uploads/img_683072998fa1d.png', link: 'https://plugplay.games/embed/689f904159247bb21bed48679913aabd9fddb0de', source: 'PlugPlay' },
  { id: 'pp-gemstone-tap', title: 'Gemstone Tap Frenzy', image: 'https://plugplay.games/data/uploads/img_683071be9c0ad.png', link: 'https://plugplay.games/embed/3d3b1f44b72b64d01c84e03a7c14b33ef397674e', source: 'PlugPlay' },
  { id: 'pp-galactic-conquest', title: 'Galactic Conquest: Space Warfare', image: 'https://plugplay.games/data/uploads/img_683071a38200f.png', link: 'https://plugplay.games/embed/2ec83dea47e65cf55e32ab0accc3de003885086f', source: 'PlugPlay' },
  { id: 'pp-free-kick', title: 'Ultimate Free Kick Challenge', image: 'https://plugplay.games/data/uploads/img_6830716fb2dbb.png', link: 'https://plugplay.games/embed/a84f57e22e40dabcb8df81bc520e814174900c0f', source: 'PlugPlay' },
  { id: 'pp-flickshot', title: 'FlickShot Champions: Soccer Challenge', image: 'https://plugplay.games/data/uploads/img_683071535f83f.jpg', link: 'https://plugplay.games/embed/1736e4fc74647ed1a01a37ab754c4f68ff45fc8c', source: 'PlugPlay' },
  { id: 'pp-brainquest', title: 'BrainQuest Academy', image: 'https://plugplay.games/data/uploads/img_6830713c4e9f8.png', link: 'https://plugplay.games/embed/24f95e94edca0cdb34e6b5deb5a1d6e9efa57b8e', source: 'PlugPlay' },
  { id: 'pp-duck-blaster', title: 'Duck Blaster: Carnival Shooter', image: 'https://plugplay.games/data/uploads/img_683071174802d.png', link: 'https://plugplay.games/embed/b3eb6586740556aeecb86104d395b102e4dc9199', source: 'PlugPlay' },
  { id: 'pp-extreme-parking', title: 'Extreme Parking Challenge', image: 'https://plugplay.games/data/uploads/img_683070fc4bb9b.png', link: 'https://plugplay.games/embed/4645a43fd822965a7ea818c263c3b68fa5058792', source: 'PlugPlay' },
  { id: 'pp-pixel-survival', title: 'Pixel Survival Craft: Apocalypse Builder', image: 'https://plugplay.games/data/uploads/img_683070e2695f9.png', link: 'https://plugplay.games/embed/b1a1e4cbcf4e6e76a5664f6ca49809cc28eacc67', source: 'PlugPlay' },
  { id: 'pp-turbo-rush', title: 'Turbo Rush: Speed Booster', image: 'https://plugplay.games/data/uploads/img_683070bcc35d0.png', link: 'https://plugplay.games/embed/3515565d88f045fa089addf569ca871381098926', source: 'PlugPlay' },
  { id: 'pp-burger-rush', title: 'Burger Rush: Fast Food Frenzy', image: 'https://plugplay.games/data/uploads/img_6830709451ed5.png', link: 'https://plugplay.games/embed/9335cca116188165e035c19ddf823d15160bc23a', source: 'PlugPlay' },
  { id: 'pp-box-stacker', title: 'Box Stacker Pro', image: 'https://plugplay.games/data/uploads/img_6830707c18a69.png', link: 'https://plugplay.games/embed/964c4270355d4b9d1fbd26f064458ee8b670829f', source: 'PlugPlay' },
  { id: 'pp-bionic-rush', title: 'Bionic Rush: Robotic Runner', image: 'https://plugplay.games/data/uploads/img_6830706466658.jpg', link: 'https://plugplay.games/embed/259069444ccdb1c354dc4ca872fb12f21dbb34b4', source: 'PlugPlay' },
  { id: 'pp-pixel-blast', title: 'Pixel Blast Arcade', image: 'https://plugplay.games/data/uploads/img_683070460b944.jpg', link: 'https://plugplay.games/embed/531e4d65fc4ba823b14e2f6ebc6affe206ee443a', source: 'PlugPlay' },
  { id: 'pp-numbermerge-challenge', title: 'NumberMerge 2048 Challenge', image: 'https://plugplay.games/data/uploads/img_6830703413aee.png', link: 'https://plugplay.games/embed/de9e7c7ada6e1c22fbc8ea8e9817a5c40989f989', source: 'PlugPlay' },
  { id: 'pp-wild-safari', title: 'Wild Safari: Animal Quests Adventure', image: 'https://plugplay.games/data/uploads/img_6830700a73b04.png', link: 'https://plugplay.games/embed/ae1f2366df87a59b1a835ff9699898d4d8d5126e', source: 'PlugPlay' },
  { id: 'pp-zombie-skull', title: 'Zombie Skull Smash: Physics Destruction', image: 'https://plugplay.games/data/uploads/img_68306fd6a1363.png', link: 'https://plugplay.games/embed/a5f9ba209dd20bdb78c6a65a8f85d9cd93cb84f9', source: 'PlugPlay' }
];

export const KONAMI_CODE = [
  'ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown',
  'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight',
  'b', 'a', 'Enter'
];
